const connectDB = require("./config/db");
const Location = require("./models/Location")

connectDB();

const tamilNaduLocations = [
  {
    district: "Chennai",
    city: "Chennai",
    type: "Metropolitan City",
    latitude: 13.0827,
    longitude: 80.2707,
  },
  {
    district: "Chennai",
    city: "Adambakkam",
    type: "Suburb",
    latitude: 13.0073,
    longitude: 80.1996,
  },
  {
    district: "Chennai",
    city: "Ambattur",
    type: "Industrial Area",
    latitude: 13.1143,
    longitude: 80.1548,
  },
  {
    district: "Chennai",
    city: "Anna Nagar",
    type: "Residential Area",
    latitude: 13.0896,
    longitude: 80.2104,
  },
  {
    district: "Chennai",
    city: "Avadi",
    type: "Cantonment",
    latitude: 13.1157,
    longitude: 80.1018,
  },
  {
    district: "Chennai",
    city: "Chromepet",
    type: "Suburb",
    latitude: 12.951,
    longitude: 80.1421,
  },
  {
    district: "Chennai",
    city: "Egmore",
    type: "Commercial Area",
    latitude: 13.079,
    longitude: 80.2599,
  },
  {
    district: "Chennai",
    city: "Guindy",
    type: "Industrial Area",
    latitude: 13.0089,
    longitude: 80.2203,
  },
  {
    district: "Chennai",
    city: "Kodambakkam",
    type: "Commercial Area",
    latitude: 13.0518,
    longitude: 80.2209,
  },
  {
    district: "Chennai",
    city: "Mylapore",
    type: "Historical Area",
    latitude: 13.0372,
    longitude: 80.2673,
  },
  {
    district: "Chennai",
    city: "Nungambakkam",
    type: "Commercial Area",
    latitude: 13.0622,
    longitude: 80.2404,
  },
  {
    district: "Chennai",
    city: "Perambur",
    type: "Industrial Area",
    latitude: 13.114,
    longitude: 80.2398,
  },
  {
    district: "Chennai",
    city: "Saidapet",
    type: "Suburb",
    latitude: 13.0215,
    longitude: 80.2246,
  },
  {
    district: "Chennai",
    city: "T. Nagar",
    type: "Commercial Area",
    latitude: 13.0418,
    longitude: 80.2341,
  },
  {
    district: "Chennai",
    city: "Tambaram",
    type: "Suburb",
    latitude: 12.9246,
    longitude: 80.1271,
  },
  {
    district: "Chennai",
    city: "Thiruvanmiyur",
    type: "Residential Area",
    latitude: 12.985,
    longitude: 80.2582,
  },
  {
    district: "Chennai",
    city: "Velachery",
    type: "Residential Area",
    latitude: 12.9791,
    longitude: 80.2203,
  },
  {
    district: "Coimbatore",
    city: "Coimbatore",
    type: "Metropolitan City",
    latitude: 11.0168,
    longitude: 76.9558,
  },
  {
    district: "Coimbatore",
    city: "Gandhipuram",
    type: "Commercial Area",
    latitude: 11.0044,
    longitude: 76.9705,
  },
  {
    district: "Coimbatore",
    city: "Peelamedu",
    type: "Educational Hub",
    latitude: 11.0279,
    longitude: 77.0228,
  },
  {
    district: "Coimbatore",
    city: "Pollachi",
    type: "Town",
    latitude: 10.6576,
    longitude: 77.0104,
  },
  {
    district: "Coimbatore",
    city: "R.S. Puram",
    type: "Residential Area",
    latitude: 11.0076,
    longitude: 76.9546,
  },
  {
    district: "Coimbatore",
    city: "Saravanampatti",
    type: "IT Hub",
    latitude: 11.0938,
    longitude: 76.9932,
  },
  {
    district: "Coimbatore",
    city: "Singanallur",
    type: "Industrial Area",
    latitude: 10.9979,
    longitude: 77.0157,
  },
  {
    district: "Coimbatore",
    city: "Sulur",
    type: "Town",
    latitude: 11.0262,
    longitude: 77.1254,
  },
  {
    district: "Coimbatore",
    city: "Tiruppur",
    type: "City",
    latitude: 11.1085,
    longitude: 77.3411,
  },
  {
    district: "Coimbatore",
    city: "Ukkadam",
    type: "Commercial Area",
    latitude: 10.9914,
    longitude: 76.9573,
  },
  {
    district: "Madurai",
    city: "Madurai",
    type: "Temple City",
    latitude: 9.9252,
    longitude: 78.1198,
  },
  {
    district: "Madurai",
    city: "Alagappan Nagar",
    type: "Residential Area",
    latitude: 9.9332,
    longitude: 78.1258,
  },
  {
    district: "Madurai",
    city: "Anna Nagar",
    type: "Residential Area",
    latitude: 9.9375,
    longitude: 78.1322,
  },
  {
    district: "Madurai",
    city: "Arappalayam",
    type: "Commercial Area",
    latitude: 9.9188,
    longitude: 78.0984,
  },
  {
    district: "Madurai",
    city: "K. K. Nagar",
    type: "Residential Area",
    latitude: 9.9577,
    longitude: 78.1361,
  },
  {
    district: "Madurai",
    city: "Simmakkal",
    type: "Commercial Area",
    latitude: 9.9198,
    longitude: 78.1229,
  },
  {
    district: "Madurai",
    city: "Tallakulam",
    type: "Commercial Area",
    latitude: 9.9418,
    longitude: 78.1125,
  },
  {
    district: "Madurai",
    city: "Thirumangalam",
    type: "Town",
    latitude: 9.8486,
    longitude: 78.0158,
  },
  {
    district: "Madurai",
    city: "Thiruparankundram",
    type: "Temple Town",
    latitude: 9.8814,
    longitude: 78.0733,
  },
  {
    district: "Madurai",
    city: "Villapuram",
    type: "Residential Area",
    latitude: 9.9282,
    longitude: 78.0958,
  },
  {
    district: "Tiruchirappalli",
    city: "Tiruchirappalli",
    type: "City",
    latitude: 10.7905,
    longitude: 78.7047,
  },
  {
    district: "Tiruchirappalli",
    city: "Ariyamangalam",
    type: "Industrial Area",
    latitude: 10.7912,
    longitude: 78.6834,
  },
  {
    district: "Tiruchirappalli",
    city: "Cantonment",
    type: "Cantonment Area",
    latitude: 10.8273,
    longitude: 78.6926,
  },
  {
    district: "Tiruchirappalli",
    city: "K. K. Nagar",
    type: "Residential Area",
    latitude: 10.8052,
    longitude: 78.6803,
  },
  {
    district: "Tiruchirappalli",
    city: "Srirangam",
    type: "Temple Town",
    latitude: 10.8626,
    longitude: 78.6915,
  },
  {
    district: "Tiruchirappalli",
    city: "Thillai Nagar",
    type: "Residential Area",
    latitude: 10.8045,
    longitude: 78.6968,
  },
  {
    district: "Salem",
    city: "Salem",
    type: "City",
    latitude: 11.6643,
    longitude: 78.146,
  },
  {
    district: "Salem",
    city: "Hasthampatti",
    type: "Commercial Area",
    latitude: 11.6572,
    longitude: 78.1345,
  },
  {
    district: "Salem",
    city: "Kondalampatti",
    type: "Industrial Area",
    latitude: 11.6862,
    longitude: 78.1115,
  },
  {
    district: "Salem",
    city: "Suramangalam",
    type: "Residential Area",
    latitude: 11.6782,
    longitude: 78.1265,
  },
  {
    district: "Salem",
    city: "Ammapet",
    type: "Industrial Area",
    latitude: 11.6502,
    longitude: 78.1428,
  },
  {
    district: "Tirunelveli",
    city: "Tirunelveli",
    type: "City",
    latitude: 8.7139,
    longitude: 77.7567,
  },
  {
    district: "Tirunelveli",
    city: "Palayamkottai",
    type: "Educational Hub",
    latitude: 8.7183,
    longitude: 77.7405,
  },
  {
    district: "Tirunelveli",
    city: "Tenkasi",
    type: "Town",
    latitude: 8.9556,
    longitude: 77.3152,
  },
  {
    district: "Tirunelveli",
    city: "Ambasamudram",
    type: "Town",
    latitude: 8.7078,
    longitude: 77.4528,
  },
  {
    district: "Erode",
    city: "Erode",
    type: "City",
    latitude: 11.341,
    longitude: 77.7172,
  },
  {
    district: "Erode",
    city: "Brough Road",
    type: "Commercial Area",
    latitude: 11.3445,
    longitude: 77.7278,
  },
  {
    district: "Erode",
    city: "Gobichettipalayam",
    type: "Town",
    latitude: 11.4549,
    longitude: 77.4422,
  },
  {
    district: "Erode",
    city: "Sathyamangalam",
    type: "Town",
    latitude: 11.505,
    longitude: 77.2383,
  },
  {
    district: "Vellore",
    city: "Vellore",
    type: "City",
    latitude: 12.9165,
    longitude: 79.1325,
  },
  {
    district: "Vellore",
    city: "Katpadi",
    type: "Educational Hub",
    latitude: 12.9762,
    longitude: 79.1328,
  },
  {
    district: "Vellore",
    city: "Sathuvachari",
    type: "Residential Area",
    latitude: 12.9252,
    longitude: 79.1408,
  },
  {
    district: "Vellore",
    city: "Bagayam",
    type: "Residential Area",
    latitude: 12.9078,
    longitude: 79.1265,
  },
  {
    district: "Thanjavur",
    city: "Thanjavur",
    type: "Temple City",
    latitude: 10.787,
    longitude: 79.1378,
  },
  {
    district: "Thanjavur",
    city: "Kumbakonam",
    type: "Temple Town",
    latitude: 10.9598,
    longitude: 79.3777,
  },
  {
    district: "Thoothukudi",
    city: "Thoothukudi",
    type: "Port City",
    latitude: 8.7642,
    longitude: 78.1348,
  },
  {
    district: "Dindigul",
    city: "Dindigul",
    type: "City",
    latitude: 10.3629,
    longitude: 77.9757,
  },
  {
    district: "Dindigul",
    city: "Batlagundu",
    type: "Town",
    latitude: 10.1716,
    longitude: 77.8152,
  },
  {
    district: "Dindigul",
    city: "Kodaikanal",
    type: "Hill Station",
    latitude: 10.2333,
    longitude: 77.4833,
  },
  {
    district: "Kanchipuram",
    city: "Kanchipuram",
    type: "Temple City",
    latitude: 12.83,
    longitude: 79.7,
  },
  {
    district: "Kanchipuram",
    city: "Chengalpattu",
    type: "Town",
    latitude: 12.6959,
    longitude: 79.9777,
  },
  {
    district: "Kanchipuram",
    city: "Sriperumbudur",
    type: "Industrial Hub",
    latitude: 12.9689,
    longitude: 79.9489,
  },
  {
    district: "Kanchipuram",
    city: "Mamallapuram",
    type: "Tourist Destination",
    latitude: 12.6264,
    longitude: 80.1722,
  },
  {
    district: "Karur",
    city: "Karur",
    type: "City",
    latitude: 10.9601,
    longitude: 78.0766,
  },
  {
    district: "Kanyakumari",
    city: "Nagercoil",
    type: "City",
    latitude: 8.1773,
    longitude: 77.4344,
  },
  {
    district: "Kanyakumari",
    city: "Kanyakumari",
    type: "Tourist Destination",
    latitude: 8.0883,
    longitude: 77.5385,
  },
  {
    district: "Namakkal",
    city: "Namakkal",
    type: "City",
    latitude: 11.2213,
    longitude: 78.1654,
  },
  {
    district: "Namakkal",
    city: "Rasipuram",
    type: "Town",
    latitude: 11.4605,
    longitude: 78.1865,
  },
  {
    district: "Theni",
    city: "Theni",
    type: "City",
    latitude: 10.0104,
    longitude: 77.4768,
  },
  {
    district: "Theni",
    city: "Bodinayakanur",
    type: "Town",
    latitude: 10.011,
    longitude: 77.3495,
  },
  {
    district: "Cuddalore",
    city: "Cuddalore",
    type: "Port City",
    latitude: 11.7447,
    longitude: 79.768,
  },
  {
    district: "Cuddalore",
    city: "Neyveli",
    type: "Industrial Town",
    latitude: 11.5483,
    longitude: 79.4716,
  },
  {
    district: "Nagapattinam",
    city: "Nagapattinam",
    type: "Port City",
    latitude: 10.7667,
    longitude: 79.8417,
  },
  {
    district: "Nagapattinam",
    city: "Velankanni",
    type: "Pilgrimage Town",
    latitude: 10.6833,
    longitude: 79.85,
  },
  {
    district: "Sivaganga",
    city: "Sivaganga",
    type: "City",
    latitude: 9.8569,
    longitude: 78.4861,
  },
  {
    district: "Sivaganga",
    city: "Karaikudi",
    type: "Town",
    latitude: 10.0667,
    longitude: 78.7833,
  },
  {
    district: "Villupuram",
    city: "Villupuram",
    type: "City",
    latitude: 11.9398,
    longitude: 79.492,
  },
  {
    district: "Villupuram",
    city: "Tindivanam",
    type: "Town",
    latitude: 12.2333,
    longitude: 79.65,
  },
  {
    district: "Ramanathapuram",
    city: "Ramanathapuram",
    type: "City",
    latitude: 9.3715,
    longitude: 78.8307,
  },
  {
    district: "Ramanathapuram",
    city: "Rameswaram",
    type: "Pilgrimage Town",
    latitude: 9.2882,
    longitude: 79.3127,
  },
  {
    district: "Pudukkottai",
    city: "Pudukkottai",
    type: "City",
    latitude: 10.381,
    longitude: 78.8214,
  },
  {
    district: "Krishnagiri",
    city: "Krishnagiri",
    type: "City",
    latitude: 12.5186,
    longitude: 78.2137,
  },
  {
    district: "Krishnagiri",
    city: "Hosur",
    type: "Industrial City",
    latitude: 12.7403,
    longitude: 77.8252,
  },
  {
    district: "Dharmapuri",
    city: "Dharmapuri",
    type: "City",
    latitude: 12.1271,
    longitude: 78.1579,
  },
  {
    district: "Nilgiris",
    city: "Ooty",
    type: "Hill Station",
    latitude: 11.4102,
    longitude: 76.695,
  },
  {
    district: "Nilgiris",
    city: "Coonoor",
    type: "Hill Station",
    latitude: 11.345,
    longitude: 76.7956,
  },
  {
    district: "Nilgiris",
    city: "Gudalur",
    type: "Hill Town",
    latitude: 11.5031,
    longitude: 76.4931,
  },
  {
    district: "Ariyalur",
    city: "Ariyalur",
    type: "Town",
    latitude: 11.1375,
    longitude: 79.0758,
  },
  {
    district: "Perambalur",
    city: "Perambalur",
    type: "Town",
    latitude: 11.2333,
    longitude: 78.8833,
  },
  {
    district: "Tiruvallur",
    city: "Tiruvallur",
    type: "City",
    latitude: 13.1446,
    longitude: 79.9081,
  },
  {
    district: "Tiruvallur",
    city: "Poonamallee",
    type: "Suburb",
    latitude: 13.0487,
    longitude: 80.1149,
  },
  {
    district: "Tiruvannamalai",
    city: "Tiruvannamalai",
    type: "Temple City",
    latitude: 12.23,
    longitude: 79.0666,
  },
  {
    district: "Virudhunagar",
    city: "Virudhunagar",
    type: "City",
    latitude: 9.5876,
    longitude: 77.9528,
  },
  {
    district: "Virudhunagar",
    city: "Sivakasi",
    type: "Industrial Town",
    latitude: 9.4492,
    longitude: 77.7973,
  },
  {
    district: "Virudhunagar",
    city: "Rajapalayam",
    type: "Town",
    latitude: 9.452,
    longitude: 77.5532,
  },
  {
    district: "Tiruvarur",
    city: "Tiruvarur",
    type: "Temple Town",
    latitude: 10.7725,
    longitude: 79.6368,
  },
  {
    district: "Tiruvarur",
    city: "Mannargudi",
    type: "Town",
    latitude: 10.6667,
    longitude: 79.4333,
  },
  {
    district: "Chennai",
    city: "Ashok Nagar",
    type: "Commercial Area",
    latitude: 13.0354,
    longitude: 80.2108,
  },
  {
    district: "Chennai",
    city: "Besant Nagar",
    type: "Residential Area",
    latitude: 13.0036,
    longitude: 80.2661,
  },
  {
    district: "Chennai",
    city: "Choolaimedu",
    type: "Residential Area",
    latitude: 13.0608,
    longitude: 80.2219,
  },
  {
    district: "Chennai",
    city: "IIT Madras",
    type: "Educational Area",
    latitude: 12.9915,
    longitude: 80.2337,
  },
  {
    district: "Chennai",
    city: "K.K. Nagar",
    type: "Residential Area",
    latitude: 13.0339,
    longitude: 80.2006,
  },
  {
    district: "Chennai",
    city: "Koyambedu",
    type: "Commercial Area",
    latitude: 13.0719,
    longitude: 80.1964,
  },
  {
    district: "Chennai",
    city: "Medavakkam",
    type: "Residential Area",
    latitude: 12.9208,
    longitude: 80.1958,
  },
  {
    district: "Chennai",
    city: "Mogappair",
    type: "Residential Area",
    latitude: 13.0811,
    longitude: 80.1794,
  },
  {
    district: "Chennai",
    city: "Nanganallur",
    type: "Residential Area",
    latitude: 12.9786,
    longitude: 80.1819,
  },
  {
    district: "Chennai",
    city: "Pallavaram",
    type: "Suburb",
    latitude: 12.9678,
    longitude: 80.1503,
  },
  {
    district: "Chennai",
    city: "Perungudi",
    type: "IT Hub",
    latitude: 12.97,
    longitude: 80.2408,
  },
  {
    district: "Chennai",
    city: "Porur",
    type: "Residential Area",
    latitude: 13.0353,
    longitude: 80.1581,
  },
  {
    district: "Chennai",
    city: "Royapettah",
    type: "Commercial Area",
    latitude: 13.0519,
    longitude: 80.265,
  },
  {
    district: "Chennai",
    city: "Sholinganallur",
    type: "IT Hub",
    latitude: 12.8992,
    longitude: 80.2278,
  },
  {
    district: "Chennai",
    city: "Teynampet",
    type: "Commercial Area",
    latitude: 13.0411,
    longitude: 80.2547,
  },
  {
    district: "Chennai",
    city: "Vadapalani",
    type: "Commercial Area",
    latitude: 13.0511,
    longitude: 80.2125,
  },
  {
    district: "Chennai",
    city: "Valasaravakkam",
    type: "Residential Area",
    latitude: 13.0467,
    longitude: 80.1667,
  },
  {
    district: "Coimbatore",
    city: "Avinashi Road",
    type: "Commercial Area",
    latitude: 11.0333,
    longitude: 77.0333,
  },
  {
    district: "Coimbatore",
    city: "Ganapathy",
    type: "Industrial Area",
    latitude: 11.0411,
    longitude: 76.9961,
  },
  {
    district: "Coimbatore",
    city: "Kalapatti",
    type: "Educational Hub",
    latitude: 11.1167,
    longitude: 77.0167,
  },
  {
    district: "Coimbatore",
    city: "Kavundampalayam",
    type: "Residential Area",
    latitude: 11.0167,
    longitude: 76.9833,
  },
  {
    district: "Coimbatore",
    city: "Mettupalayam",
    type: "Town",
    latitude: 11.2998,
    longitude: 76.9447,
  },
  {
    district: "Coimbatore",
    city: "Neelambur",
    type: "Industrial Area",
    latitude: 11.0833,
    longitude: 77.0833,
  },
  {
    district: "Coimbatore",
    city: "Periyanaickenpalayam",
    type: "Residential Area",
    latitude: 11.1167,
    longitude: 76.9167,
  },
  {
    district: "Coimbatore",
    city: "Podanur",
    type: "Residential Area",
    latitude: 10.9333,
    longitude: 76.9667,
  },
  {
    district: "Coimbatore",
    city: "Saibaba Colony",
    type: "Residential Area",
    latitude: 11.0181,
    longitude: 76.9508,
  },
  {
    district: "Coimbatore",
    city: "Vadavalli",
    type: "Residential Area",
    latitude: 11.0167,
    longitude: 76.9167,
  },
  {
    district: "Madurai",
    city: "Anaiyur",
    type: "Residential Area",
    latitude: 9.95,
    longitude: 78.1,
  },
  {
    district: "Madurai",
    city: "Arasaradi",
    type: "Residential Area",
    latitude: 9.9167,
    longitude: 78.1333,
  },
  {
    district: "Madurai",
    city: "Kochadai",
    type: "Residential Area",
    latitude: 9.9333,
    longitude: 78.0667,
  },
  {
    district: "Madurai",
    city: "Pasumalai",
    type: "Residential Area",
    latitude: 9.9,
    longitude: 78.15,
  },
  {
    district: "Madurai",
    city: "Thirunagar",
    type: "Residential Area",
    latitude: 9.9667,
    longitude: 78.1167,
  },
  {
    district: "Madurai",
    city: "Vandiyur",
    type: "Residential Area",
    latitude: 9.9167,
    longitude: 78.15,
  },
  {
    district: "Tiruchirappalli",
    city: "Bharathidasan Nagar",
    type: "Residential Area",
    latitude: 10.8167,
    longitude: 78.6833,
  },
  {
    district: "Tiruchirappalli",
    city: "Golden Rock",
    type: "Industrial Area",
    latitude: 10.7833,
    longitude: 78.6833,
  },
  {
    district: "Tiruchirappalli",
    city: "Puthur",
    type: "Suburb",
    latitude: 10.7782,
    longitude: 78.7163,
  },
  {
    district: "Salem",
    city: "Annur",
    type: "Town",
    latitude: 11.2362,
    longitude: 77.1043,
  },
  {
    district: "Salem",
    city: "Fairlands",
    type: "Residential Area",
    latitude: 11.6667,
    longitude: 78.1333,
  },
  {
    district: "Salem",
    city: "Mettur",
    type: "Industrial Town",
    latitude: 11.8,
    longitude: 77.8,
  },
  {
    district: "Salem",
    city: "Yercaud",
    type: "Hill Station",
    latitude: 11.7833,
    longitude: 78.2,
  },
  {
    district: "Tirunelveli",
    city: "Cheranmahadevi",
    type: "Town",
    latitude: 8.6667,
    longitude: 77.5333,
  },
  {
    district: "Tirunelveli",
    city: "Sankarankovil",
    type: "Temple Town",
    latitude: 9.15,
    longitude: 77.55,
  },
  {
    district: "Erode",
    city: "Bhavani",
    type: "Town",
    latitude: 11.45,
    longitude: 77.6833,
  },
  {
    district: "Erode",
    city: "Chennimalai",
    type: "Town",
    latitude: 11.1667,
    longitude: 77.6167,
  },
  {
    district: "Erode",
    city: "Perundurai",
    type: "Industrial Hub",
    latitude: 11.2667,
    longitude: 77.5833,
  },
  {
    district: "Vellore",
    city: "Ambur",
    type: "Industrial Town",
    latitude: 12.7833,
    longitude: 78.7167,
  },
  {
    district: "Vellore",
    city: "Arcot",
    type: "Historical Town",
    latitude: 12.9,
    longitude: 79.3333,
  },
  {
    district: "Vellore",
    city: "Gudiyatham",
    type: "Town",
    latitude: 12.95,
    longitude: 78.8667,
  },
  {
    district: "Vellore",
    city: "Ranipet",
    type: "Industrial Town",
    latitude: 12.9333,
    longitude: 79.3333,
  },
  {
    district: "Vellore",
    city: "Tirupattur",
    type: "Town",
    latitude: 12.5,
    longitude: 78.5667,
  },
  {
    district: "Thanjavur",
    city: "Pattukkottai",
    type: "Town",
    latitude: 10.4333,
    longitude: 79.3167,
  },
  {
    district: "Thoothukudi",
    city: "Kovilpatti",
    type: "Industrial Town",
    latitude: 9.1667,
    longitude: 77.8667,
  },
  {
    district: "Thoothukudi",
    city: "Tiruchendur",
    type: "Temple Town",
    latitude: 8.5,
    longitude: 78.1167,
  },
  {
    district: "Dindigul",
    city: "Oddanchatram",
    type: "Town",
    latitude: 10.4833,
    longitude: 77.75,
  },
  {
    district: "Dindigul",
    city: "Palani",
    type: "Temple Town",
    latitude: 10.45,
    longitude: 77.5333,
  },
  {
    district: "Kanchipuram",
    city: "Tiruporur",
    type: "Town",
    latitude: 12.7156,
    longitude: 80.2031,
  },
  {
    district: "Karur",
    city: "Kulithalai",
    type: "Town",
    latitude: 10.8399,
    longitude: 78.2074,
  },
  {
    district: "Kanyakumari",
    city: "Marthandam",
    type: "Commercial Hub",
    latitude: 8.3,
    longitude: 77.2167,
  },
  {
    district: "Kanyakumari",
    city: "Padmanabhapuram",
    type: "Historical Town",
    latitude: 8.2333,
    longitude: 77.3333,
  },
  {
    district: "Theni",
    city: "Chinnamanur",
    type: "Town",
    latitude: 9.8333,
    longitude: 77.3833,
  },
  {
    district: "Theni",
    city: "Periyakulam",
    type: "Town",
    latitude: 10.1167,
    longitude: 77.55,
  },
  {
    district: "Cuddalore",
    city: "Chidambaram",
    type: "Temple Town",
    latitude: 11.3994,
    longitude: 79.6911,
  },
  {
    district: "Cuddalore",
    city: "Panruti",
    type: "Town",
    latitude: 11.7667,
    longitude: 79.55,
  },
  {
    district: "Nagapattinam",
    city: "Mayiladuthurai",
    type: "Temple Town",
    latitude: 11.1,
    longitude: 79.65,
  },
  {
    district: "Nagapattinam",
    city: "Sirkazhi",
    type: "Temple Town",
    latitude: 11.2372,
    longitude: 79.7356,
  },
  {
    district: "Sivaganga",
    city: "Devakottai",
    type: "Town",
    latitude: 9.95,
    longitude: 78.8167,
  },
  {
    district: "Villupuram",
    city: "Gingee",
    type: "Historical Town",
    latitude: 12.25,
    longitude: 79.4167,
  },
  {
    district: "Ramanathapuram",
    city: "Paramakudi",
    type: "Town",
    latitude: 9.55,
    longitude: 78.6,
  },
  {
    district: "Pudukkottai",
    city: "Aranthangi",
    type: "Town",
    latitude: 10.1667,
    longitude: 78.9833,
  },
  {
    district: "Krishnagiri",
    city: "Denkanikottai",
    type: "Town",
    latitude: 12.5333,
    longitude: 77.8,
  },
  {
    district: "Dharmapuri",
    city: "Harur",
    type: "Town",
    latitude: 12.0667,
    longitude: 78.5,
  },
  {
    district: "Nilgiris",
    city: "Kotagiri",
    type: "Hill Town",
    latitude: 11.4167,
    longitude: 76.8667,
  },
  {
    district: "Virudhunagar",
    city: "Aruppukkottai",
    type: "Town",
    latitude: 9.5167,
    longitude: 78.1,
  },
  {
    district: "Tiruvarur",
    city: "Thiruthuraipoondi",
    type: "Town",
    latitude: 10.55,
    longitude: 79.6333,
  },
  {
    district: "Krishnagiri",
    city: "Pochampalli",
    type: "Town",
    latitude: 12.35,
    longitude: 78.2667,
  },
];

const insertTamilNaduLocations = async (req, res) => {
  try {
    // Clear existing data (optional)
    await Location.deleteMany({ state: "Tamil Nadu" });

    // Insert all locations
    const result = await Location.insertMany(
      tamilNaduLocations.map((location) => ({
        ...location,
        state: "Tamil Nadu",
      }))
    );

    res.status(201).json({
      success: true,
      message: `${result.length} Tamil Nadu locations inserted successfully`,
      data: result,
    });
  } catch (error) {
    console.error("Error inserting locations:", error);
    res.status(500).json({
      success: false,
      message: "Failed to insert locations",
      error: error.message,
    });
  }
};

insertTamilNaduLocations()
